### ISSUE TITLE
amazon-elb/sg-843f59ed

### ISSUE THREAD

**Issue by brianeclow** [undeadlabs/holepunch#7]
How does one reference the ELB SG?

**Comment by gamepoet** [comment]
I would imagine you would have to reference the security group by name. Note that we never actually tried that situation with this software so it may not work. Once we started working with ELBs, we switched over to using terraform (https://www.terraform.io).

**Comment by brianeclow** [comment]
We are in the process of moving over to terraform, however, in the meantime, I am still trying to maintain our legacy systems. Which leaves me in a bit out of sorts with our existing orchestration tool which uses holepunch.

I attempted to reference the ELB like 'amazon-elb/sg-843f59ed', 'sg-843f59ed', 'amazon-elb/amazon-elb-sg', and 'amazon-elb-sg'. None of them worked. They all failed the verification of an existing SG containing the ELB.

Is there another method to reference it?

**Comment by brianeclow** [comment]
Dead project. Closing.
